<div class="container-adm d-flex justify-content-center flex-column align-items-center">
   
    <section class="login-adm col-6 d-flex justify-content-center flex-column align-content-center">
        <h1 class="text-center">Login Administrativo</h1>
        <form class="col-12 m-0 p-0" action="/autenticar" method="post"> <!-- ação que encaminha os dados para a parte do servidor -->
            <div class="form-group"> <!-- method post: usado para deixar menos vunerável os dados do cliente, ao contrário do metodo get(que é o padrão) -->
                <label class="bold" for="email">Email:</label>
                <input name="email" id="email" type="email" class="form-control" placeholder="E-mail">
            </div> <!-- por meio do name, o servidor transforma as informações passadas em parâmetros para a page do servidor php (aparece na url de início) -->
            <div class="form-group">
                <label class="bold" for="senha">Senha:</label>
                <input name="senha" id="senha" type="password" class="form-control" placeholder="Senha">
            </div>
            <? if($this->view->login == 'erro') { ?>
                <div class="row">
                    <div class="col">
                        <span class="text text-white animate__animated animate__headShake position-absolute">Email e/ou senha inválido(s)!</span>
                    </div>
                </div>
            <? } ?>
            <? 
                // fazendo novo teste: se erro2(ou seja, as páginas protegidas forem buscadas sem ter o acesso autenticado) ocorrer, chama essa página com essa mensagem
                if(isset($_GET['login']) && $_GET['login'] == 'erro2'){ // verifica se o índice estã setado(ativo)

            ?>

            <div class="text-white pb-3">
                Autentifique a permissão antes de tentar acessar essa página protegida
            </div>

            <? } ?> 

            <button class="col-12 col-xl-7 btn btn-info btn-block mt-4 " type="submit">Entrar</button>
        </form>  
    </section>
</div>

