
<!-- SEÇÃO 1 -------------------------------------------------------------------------------------------------------------------->
<div id="conteudo" class="col-8 m-0 p-5 float-left mt-0">
    <main class="col-12 float-left mb-5 mt-5">
        <section class="d-flex justify-content-center align-content-center row mt-0">
            <div class="col-12 p-1 mb-4">
                <div class="row">
                    <div class="col-12 align-content-center mb-0 pb-4">      
                        <h2 class="text-center pb-0 mb-0">Me siga no Instagram</h2>
                        <img src="imagens/fundo-rodape.png" height="2px" width="100%" class="mb-1">
                        <p class="text-left pl-5">Lá eu posto novidades e curiosidades
                        sobre fanfics, livros, etc.</p>      
                    </div>      
                </div>     
                <a href="https://www.instagram.com/fabulaslunares/">
                    <div class="box-divulgacao">
                        <div id="myCarousel" class="carousel slide d-flex justify-content-center" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#myCarousel" data-slide-to="0" class="active ind"></li>
                                <li data-target="#myCarousel" data-slide-to="1" class="ind"></li>
                                <li data-target="#myCarousel" data-slide-to="2" class="ind"></li>
                            </ol>
                            
                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">                    
                                <div class="carousel-item active">
                                    <img src="imagens/c2.png" alt="">
                                </div>
                                <div class="carousel-item">
                                    <img src="imagens/c3.png" alt="">
                                </div>
                                <div class="carousel-item">
                                    <img src="imagens/c4.png" alt="">
                                </div>
                            </div>
                            
                            <!-- Left and right controls -->
                            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </a>
            </div>
                <div class="col-12 justify-content-center">
                <h4 class="col-12 text-center mt-3">Deixe sua mensagem!</h4>
                <form class="col-12 mt-2">
                    <div class="row"> 
                        <p class="col-12 text-center">Se quiser entrar em contato, deixe sua mensagem e responderei por email ou pelo whatsapp.</p>
                        <div class="col-6">
                            <input type="text" class="form-control mb-2 w-100" placeholder="Digite seu nome">
                            <input type="email" class="form-control mb-2" id="email1" aria-describedby="emailHelp" placeholder="Digite seu email">
                            <input type="tel" class="form-control" id="tel1" aria-describedby="tel" placeholder="Digite seu telefone">
                        </div>
                        <div class="col-6">
                            <textarea class="form-control w-100 h-100" id="exampleFormControlTextarea1" rows="3" placeholder="Mensagem"></textarea>
                        </div>
                    </div>
                </form> 
            </div>
        </section>  
    </main>     
</div>
  
        