
<div id="conteudo" class="col-8 m-0 p-5 float-left mt-0">
    <main class="col-12 float-left mb-5 mt-3">
        <section class="d-flex justify-content-center align-content-center row mt-0">
        <!-- Código PHP ----------------------------------------------------------------------------------------------------->
        <?php foreach($this->view->dados as $key => $dicas){ ?>
            <div class="col-12 p-1 mb-4">
                <div class="row">
                    <div class="col-12 align-content-center mb-0 pb-4">      
                        <h2 class="text-center pb-0 mb-0"><?= $dicas['titulo']?></h2>
                        <img src="imagens/fundo-rodape.png" height="2px" width="100%" class="mb-1"> 
                        <p class="text-left pl-5"><?= $dicas['descricao']?></p>     
                    </div>      
                </div> 
            </div>   
        <? } ?>         
        </section>
    </main>
</div>

  