<section class="col-11 p-0 mx-auto">
      <div class="container-slide">
        <div class="action-button" id="previous">&laquo</div>
        <div class="container-items" id="container-items"></div>
        <div class="action-button" id="next">&raquo</div>
      </div>
</section>
<div id="conteudo" class="col-8 m-0 p-5 float-left mt-0">
    <div class="col-12 float-left mb-5 mt-5">
        <div class="d-flex justify-content-center flex-column row" id="publicacoes">
            <h2 class="col-12 text-center">Exemplo de uma publicação</h2>
            <img src="imagens/fundo-rodape.png" height="2px" width="100%" class="col-12">
            <span class="subtitulo mb-4 mt-2 col-12">"Se for ler, não vá com muita sede ao pote."</span>
            <div class="textPost col-12 px-3 mx-auto rounded">
                <p class="text-indent">Curabitur maximus odio ac hendrerit scelerisque. Nunc finibus turpis in diam fringilla sollicitudin. Donec molestie commodo risus, quis egestas nulla sollicitudin sit amet. Aliquam in leo lectus. Duis vulputate turpis in dui convallis dignissim. Sed et libero vitae nisi semper pharetra. Vivamus et ipsum nec mi dictum consectetur. </p>
                <img class="rounded mx-auto col-12  mb-3 p-0" src="imagens/corte_de_espinhos.jpg" width="100%" height="auto">
                <p class="text-indent">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a hendrerit arcu. Vivamus maximus lacus odio, non accumsan diam consectetur sit amet. Curabitur posuere erat a arcu sollicitudin, consectetur bibendum urna vulputate. In ac odio non leo efficitur hendrerit a eu massa. Pellentesque congue, risus non efficitur facilisis, arcu dui elementum risus, eu tempor metus dolor nec enim. </p>
                <p class="text-indent">Fusce sapien magna, luctus quis elit eu, ultrices bibendum quam. Mauris sed lacus eget tortor posuere ultricies non non risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In ac urna dolor. Praesent nec lobortis dolor. Nullam vitae metus et est vestibulum mattis. Vivamus vulputate in velit sit amet tempus. Vestibulum egestas bibendum dui, non dictum dolor luctus eu. Vestibulum eget lectus ante. Sed placerat vel erat non interdum. In hac habitasse platea dictumst.</p>
            </div>
            <blockquote class="text-info ml-3">Publicado em: <cite>25/10/2021</cite></blockquote>
            <div id="tags" class="mb-5 pb-5">
                <p class="mb-0 font-weight-bold font-italic pb-1">Mais do gênero:</p>
                <a href="#"><span class="tags">Fantasia</span></a><a href="#"><span class="tags">Dark Side</span></a>
                <a href="#"><span class="tags">Jovem Adulto</span></a><a href="#"><span class="tags">Resenhas</span></a>
                <a href="#"><span class="tags">Nacionais</span></a><a href="#"><span class="tags">Romance</span></a>
            </div>
        </div>
        <div class="d-flex justify-content-center flex-column row" id="publicacoes">
                <h2 class="col-12 text-center">Exemplo de outra publicação</h2>
                <img src="imagens/fundo-rodape.png" height="2px" width="100%" class="col-12">
                <span class="subtitulo mb-4 mt-2 col-12">"A história de Suzie e sua família vai mudar algo dentro de você."</span>
            <div class="textPost col-12 row px-3 mx-auto rounded">                 
                <img class="rounded col-4 p-0 float-left" src="imagens/ohobbit.jpg" width="100%" height="auto">
                <p class="text-indent float-left col-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a hendrerit arcu. Vivamus maximus lacus odio, non accumsan diam consectetur sit amet. Curabitur posuere erat a arcu sollicitudin, consectetur bibendum urna vulputate. In ac odio non leo efficitur hendrerit a eu massa. Pellentesque congue, risus non efficitur facilisis, arcu dui elementum risus, eu tempor metus dolor nec enim. <br><br> Curabitur maximus odio ac hendrerit scelerisque. Nunc finibus turpis in diam fringilla sollicitudin. Donec molestie commodo risus, quis egestas nulla sollicitudin sit amet. Aliquam in leo lectus. Sed placerat vel erat non interdum. In hac habitasse platea dictumst. Sed placerat vel erat non interdum. In hac habitasse platea dictumst.</p>
                <p class="text-indent float-left">Fusce sapien magna, luctus quis elit eu, ultrices bibendum quam. Mauris sed lacus eget tortor posuere ultricies non non risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In ac urna dolor. Praesent nec lobortis dolor. Nullam vitae metus et est vestibulum mattis. Vivamus vulputate in velit sit amet tempus. Vestibulum egestas bibendum dui, non dictum dolor luctus eu. Vestibulum eget lectus ante. Sed placerat vel erat non interdum. In hac habitasse platea dictumst.</p>
            </div>
            <blockquote class="text-info ml-3">Publicado em: <cite>03/10/2021</cite></blockquote>
            <div id="tags" class="mb-5 pb-5">
                <p class="mb-0 font-weight-bold font-italic pb-1">Mais do gênero:</p>
                <a href="#"><span class="tags">Fantasia</span></a><a href="#"><span class="tags">Internacionais</span></a>
                <a href="#"><span class="tags">Jovem Adulto</span></a><a href="#"><span class="tags">Resenhas</span></a>
                <a href="#"><span class="tags">Críticas</span></a><a href="#"><span class="tags">Aventura</span></a>
            </div>
        </div>
    </div>
</div>