<div id="conteudo" class="col-8 m-0 p-5 float-left mt-0">
    <main class="col-12 float-left mb-5 mt-3">
        <div class="d-flex justify-content-center align-content-center row pt-5">
            <h4 class="col-10 text-center font-italic m-3">Ops! Não criamos este espaço ainda...</h4>
            <img class="col-6 justify-content-center" src="imagens/Em-contrucao-removebg-preview.png">
        </div>
    </main>
</div>