<div class="container-fluid d-flex">
	<div class="menu-aberto"></div>
	<div class="container-quando-maberto col-10 p-4">
		<h1 class="titulo-secao mx-4"><?=$this->view->nome?></h1>
		<section class="col-12 d-flex justify-content-around flex-column">
			<h2>Selecione um novo arquivo de imagem</h2>

			<div class="card add-midia text-center rounded-circle my-3"><i class="fas fa-plus fa-2x"></i></div>
			<button class="galeria-midia btn btn-info my-4">Galeria</button>
			<div class="form-midia">
				<form enctype="multipart/form-data" action="/adm_set_midia" method="post">
					<label for="descricao">Descrição</label>
					<div><input class="m-2 form-control descricao-midia" name="descricao" type="textarea"/></div>
					<div><input class="m-2" required name="arquivo" type="file"/></div>
					<label>Tamanho</label>
					<select name="tamanho" class="form-control select-midia">
						<option value="155">Capa de livro</option>
						<option value="250">Pequeno</option>
						<option value="450">Médio</option>
						<option value="650">Grande</option>
					</select>
					<div><input class="m-2" type="submit"/></div>
				</form>
			</div>
			
			<div class="galeria-container d-flex justify-content-around align-items-baseline flex-wrap"></div>
		</section>
	</div>
</div>

