<div class="container-fluid p-4">
	<h1 class="titulo-secao"><?=$this->view->nome?></h1>
	<section class="col-12 d-flex justify-content-center">
		<div class="card col-10 p-5 d-flex justify-content-center">
			<form method="post" action="/registra_post">
				<div class="form-group col-8 p-3">
                    <input name="Título" type="text" class="form-control" placeholder="Título" id="titulo">
                </div>
				<div class="form-group col-8 d-flex justify-content-around">
					<div class="form-group col-4">
						<label>Tipo</label>
						<select name="tipo" class="form-control" id="tipo_post">
							<option>Resenha</option>
							<option>Dica</option>
							<option>Tradução</option>
						</select>
                    </div>
					<div class="form-group col-4">
						<div class="form-group">
							<label>Categoria</label>
							<select name="categoria" class="form-control" id="categoria_post">
								<option>Ficção Científica</option>
								<option>Romance</option>
								<option>Aventura</option>
							</select>
						</div>
					</div>
                </div>
				<div class="form-group col-12 p-3">
					<textarea name="conteudo" class="form-control" rows="20" placeholder="Conteúdo" id="conteudo"></textarea>
				</div>
			</form>
		</div>
		
	</section>
</div>