<!doctype html>
<html lang="pt-br" id="inicio">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!--folha de estilo--> 
    <link rel="stylesheet" type="text/css" href="estilo.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome CSS -->
    <script src="https://kit.fontawesome.com/bf49d14db6.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    
    <title>Fábulas Lunares</title>

  </head>

  <body id="body">
    <div id="indicador"></div>
    <a href="#inicio" class="sobe"><i class="fas fa-angle-double-up"></i></a>
    <header> 
      <img class="img-fluid" src="">
      <div class="container"> <!-- cria um container responsivo --> 
        <!-- imagem da logo --> 
        <!-- class que deixa responsivo a imagem -->
        
        <h1 class="text-center p-header ban">
          Fábulas Lunares
        </h1>
        <div class="row d-flex linha-inicio flex-column justify-content-center align-content-center mb-5">
          <img src="imagens/fundo-rodape.png" height="2px" class="col-10 mb-3">
          <div class="redes col-10">
            <div class="ic" onmouseenter="icEnter(this)" id="tw">
                <a href="https://twitter.com/fabulaslunares">
                    <i class="fab fa-twitter fa-1x"></i>
                </a> 
            </div>
            <div class="ic" onmouseenter="icEnter(this)" id="insta">
              <a href="https://www.instagram.com/fabulaslunares/">
                  <i class="fab fa-instagram fa-1x"></i>
              </a> 
            </div>
            <div class="ic" onmouseenter="icEnter(this)" id="sk">
                <a href="https://www.skoob.com.br/usuario/8388418-lavs">
                  <i class="fas fa-book fa-1x"></i>
                </a> 
            </div>
          </div>
        </div>
        <nav> <!-- navbar menu -->
          <ul class="nav justify-content-center">
            <li class="nav-item mx-3">
              <a class="nav-link h5 text-center" href="/">
                <i class="far fa-newspaper fa-2x pb-2"></i>
                <p>Publicações</p>
              </a>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link h5 text-center" href="/traducoes">
                <i class="fas fa-language fa-2x pb-2"></i>
                <p>Traduções</p>
              </a>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link h5 text-center" href="/parceiros">
                <i class="fas fa-user-friends fa-2x pb-2"></i>
                <p>Parceiros</p>
              </a>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link h5 text-center" href="/contatos">                
                <i class="far fa-address-card fa-2x pb-2"></i>
                <p>Contatos</p>
              </a>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link h5 text-center" href="/dicas">
                <i class="far fa-lightbulb fa-2x pb-2"></i>
                <p>Dicas</p>
              </a>
            </li>
          </ul>
        </nav>
      </div>     
    </header>
     <!-- verifica se a página requisitada é igual a index, se for exibe o carrossel -->
     
    <div class="col-12 text-center"><a href="/natal" class="natal m-0 d-none">Click me</a>
    <div class="container-fluid row d-0 p-0 m-0">  
      <?= $this->content() ?>
      <aside class="col-4 mt-5 float-right p-5">     
          <div class="row d-flex flex-column align-content-center mb-5">
            <h4 class="col-12 text-center">Tags</h4>
            <img src="imagens/fundo-rodape.png" height="2px" class="col-12 mb-3">
            <div id="tags" class="col-12 d-flex align-items-center justify-content-center flex-wrap">
                <a href="#"><span class="tags">Fantasia</span></a><a href="#"><span class="tags">Terror</span></a>
                <a href="#"><span class="tags">Internacionais</span></a><a href="#"><span class="tags">Dorama</span></a>
                <a href="#"><span class="tags">Dark Side</span></a><a href="#"><span class="tags">Suspense</span></a>
                <a href="#"><span class="tags">Aventura</span></a><a href="#"><span class="tags">Jovem Adulto</span></a>
                <a href="#"><span class="tags">Netflix</span></a><a href="#"><span class="tags">Adulto</span></a>
                <a href="#"><span class="tags">Os Bridgertons</span></a><a href="#"><span class="tags">Harry Potter</span></a>
                <a href="#"><span class="tags">Curiosidades</span></a><a href="#"><span class="tags">Críticas</span></a>
                <a href="#"><span class="tags">Resenhas</span></a><a href="#"><span class="tags">Nacionais</span></a>
                <a href="#"><span class="tags">Romance</span></a><a href="#"><span class="tags">Livros em Promoções</span></a>
                <a href="#"><span class="tags">Notícias</span></a><a href="#"><span class="tags">Lançamentos</span></a><a href="#"><span class="tags">Amazon</span></a>
            </div>  
          </div>
          <div class="row d-flex flex-column align-content-center mb-5">
            <h4 class="col-12 text-center">Busque Aqui</h4>
            <img src="imagens/fundo-rodape.png" height="2px" class="col-12 mb-3">
            <div id="procurar" class="col-12 d-flex justify-content-center">
                <form class="d-flex">
                    <input class="form-control me-2 p-2" type="search" placeholder="Digite aqui" aria-label="Search">
                    <button class="btn btn-outline-primary p-1 px-3" type="submit">Procurar</button>
                </form>
            </div>
          </div>
        
          <div id="maisLidos" class="row d-flex flex-column align-content-center mb-5">
            <h4 class="col-12 text-center">Mais lidos</h4>
            <img src="imagens/fundo-rodape.png" height="2px" class="col-12 mb-3">
            <a href="#" class="col-12 m-0 p-0 d-flex flex-column justify-content-center mb-3 text-decoration-none">
                <div class="col-12">
                    <img class="col-12 float-left mb-2" src="imagens/Design sem nome.png" alt=""/>
                    <h5 class=" col-12 text-center mb-1">Corte De Espinhos e Rosas</h5>
                    <div class="col-12 float-left d-flex justify-content-between text-center">
                        <p><span>[Resenha]</span> Se for ler, não vá com muita sede ao pote.</p>
                    </div>
                </div>
            </a>
            <a href="#" class="col-12 m-0 p-0 d-flex flex-column justify-content-center text-decoration-none">
                <div class="col-12">
                    <img class="col-12 float-left mb-2" src="imagens/uma_vida_interrompida-slide.jpg" alt=""/>
                    <h5 class=" col-12 text-center mb-1 ">Uma Vida Interrompida</h5>
                    <div class="col-12 float-left d-flex justify-content-between text-center mb-0 ">
                        <p class=""><span>[Resenha]</span> A história de Suzie e sua família vai mudar algo dentro de você.</p>
                    </div>
                </div>
              </a>
          </div>
          <div class="row d-flex flex-column align-content-center mb-5">
            <h4 class="col-12 text-center">Faça uma Busca por Data</h4>
            <img src="imagens/fundo-rodape.png" height="2px" class="col-12 mb-3">
            <div class="col-12 d-flex justify-content-center">
                <select class="form-select" aria-label="Default select example">
                    <option selected>Publicações em Ordem de Postagem</option>
                    <option value="1">novembro de 2021 (2)</option>
                    <option value="2">Outubro de 2021 (4)</option>
                    <option value="3">Setembro de 2021 (1)</option>
                    <option value="1">Agosto de 2021 (5)</option>
                    <option value="2">Julho de 2021 (10)</option>
                    <option value="3">Junho de 2021 (5)</option>
                    <option value="3">Maio de 2021 (1)</option>
                    <option value="3">Abril de 2021 (2)</option>
                    <option value="2">Março de 2021 (7)</option>
                    <option value="3">Fevereiro de 2021 (4)</option>
                    <option value="3">Janeiro de 2021 (10)</option>
                    <option value="3">Dezembro de 2021 (10)</option>
                </select>
            </div>
          </div>  
      </aside>
      <footer id="footer" class=" row d-flex justify-content-center">
          <img src="imagens/fundo-rodape.png" height="2px" class="col-12 mb-3">
          <p class="col-8 text-uppercase font-weight-bold text-center">Todos os direitos reservados. &copy; Copyright 2021. Feito por Yves Lima.</p>
      </footer>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="site.js"></script>
  </body>
</html>




