
<!doctype html>
<html lang="pt-br" id="inicio">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!--folha de estilo--> 
    <link rel="stylesheet" type="text/css" href="estilo.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome CSS -->
    <script src="https://kit.fontawesome.com/bf49d14db6.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    
    <title>Fábulas Lunares</title>

  </head>

  <body class="bg-adm d-flex">
    <div class="menu-lateral-adm">
        <ul class="p-0 mt-5">
            <a class="menu-items" href="/adm" id="painel">
                <span class="p-0 hover-menu-item"></span>
                <i class="fas fa-pager px-1"></i>
                <span class="px-1">Painel</span>
            </a>
        
            <a class="menu-items" href="/adm_posts" id="posts">
                <span class="p-0 hover-menu-item"></span>
                <i class="fa-solid fa-thumbtack px-2"></i>
                <span>Posts</span>
            </a>
            <a class="menu-items" href="/adm_midia" id="midia">
                <span class="p-0 hover-menu-item"></span>
                <i class="fa-solid fa-photo-film px-1"></i>
                <span>Mídia</span>
            </a>
            <a class="menu-items" href="/adm_comentarios" id="comentarios">
                <span class="p-0 hover-menu-item"></span>
                <i class="fa-solid fa-comments px-1"></i>
                <span>Comentários</span>
            </a>
            <a class="menu-items" href="/sair">
                <span class="p-0 hover-menu-item"></span> 
                <i class="fa-solid fa-arrow-right-from-bracket px-1"></i>
	            <span>Sair</span>
            </a>
        </ul>
        <button class="prev-menu-adm" value="1"><i class="fas fa-angle-double-left fa-2x"></i></button>
    </div>
    
    <?= $this->content() ?>
 
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="adm.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    
</body>
</html>




